export type ProjectKind = "g" | "s";

export interface IndexedProject {
  name: string;
  sector: string;
  context: "Professionnel" | "Freelance" | "Stage" | "Formation";
  stack: string;
  url: string;
  /** À quoi sert le projet, en une phrase compréhensible par un visiteur non technique. */
  purpose: string;
  /** Pourquoi il compte : le bénéfice concret pour ses utilisateurs. */
  impact: string;
  /** g = gestion et back-office, s = sites et plateformes. */
  kind: ProjectKind;
  /** Visuel du projet (logo ou capture) dans public/assets/image. Absent = monogramme. */
  image?: string;
}

/** Tous les projets livrés, dans l'ordre d'affichage de l'index. `url` vide = projet interne. */
export const PROJECTS: readonly IndexedProject[] = [
  { name: "Turbo ERP", image: "/assets/image/turbo.png", purpose: "Un seul logiciel pour piloter une entreprise de livraison : ressources humaines, finances, logistique et reporting.", impact: "Les données de l’entreprise sont centralisées et les opérations internes se traitent plus vite.", sector: "ERP", context: "Professionnel", stack: "NestJS · Next.js · PostgreSQL", url: "https://admin-erp.turbodeliveryapp.com/analystics", kind: "g" },
  { name: "Turbo Finance", image: "/assets/image/turbo.png", purpose: "Suivi des transactions et rapports comptables d’une entreprise, relié à l’ERP par des APIs sécurisées.", impact: "Chaque flux financier est tracé et les rapports comptables se produisent automatiquement.", sector: "Finance", context: "Professionnel", stack: "NestJS · Next.js · PostgreSQL", url: "https://admin-erp.turbodeliveryapp.com/analystics", kind: "g" },
  { name: "Chicken-Nation", image: "/assets/image/logo_chiken.png", purpose: "Site officiel de la chaîne de restauration rapide, avec un système de commande en ligne et un back-office pour suivre les commandes.", impact: "Le client commande sans file d’attente et l’équipe gère les commandes en temps réel.", sector: "Restauration", context: "Professionnel", stack: "Next.js · NestJS · PostgreSQL", url: "https://www.chicken-nation.com/fr", kind: "s" },
  { name: "Sidi Immobilier", image: "/assets/image/sidi_logo.png", purpose: "Plateforme pour présenter et gérer les biens d’une agence immobilière.", impact: "La vente immobilière se digitalise et les demandes de clients sont traitées plus rapidement.", sector: "Immobilier", context: "Professionnel", stack: "Next.js · NestJS · PostgreSQL", url: "https://sidi.lunion-lab.com/fr", kind: "s" },
  { name: "Luxury Home Abidjan", image: "/assets/image/lhaa_logo.png", purpose: "Site élégant dédié aux logements de luxe à Abidjan.", impact: "Une présence en ligne premium, qui attire une clientèle haut de gamme et génère des demandes qualifiées.", sector: "Immobilier haut de gamme", context: "Professionnel", stack: "Next.js · NestJS · PostgreSQL", url: "https://luxuryhomeabidjan.com/", kind: "s" },
  { name: "Lunion-Lab Website", image: "/assets/image/logo_lunion.png", purpose: "Site officiel de l’entreprise : ses services, ses réalisations et ses contacts.", impact: "Il renforce l’image de marque et rend l’entreprise visible en ligne (Lighthouse supérieur à 90).", sector: "Site corporate", context: "Professionnel", stack: "Next.js · TypeScript · Tailwind", url: "https://www.lunion-lab.com/", kind: "s" },
  { name: "Catholikia", image: "/assets/image/catholikia.png", purpose: "Application pour la communauté catholique : activités, services et événements des paroisses au même endroit.", impact: "Les services paroissiaux se digitalisent, ce qui facilite la communication avec les fidèles.", sector: "Plateforme communautaire", context: "Professionnel", stack: "Next.js · NestJS · MongoDB", url: "https://catholikia.com/fr", kind: "s" },
  { name: "OSA FC", image: "/assets/image/osa_logo.png", purpose: "Site officiel du club de football : présentation du club, matchs et actualités.", impact: "Le club gagne une vitrine officielle et garde le lien avec ses supporters.", sector: "Sport", context: "Professionnel", stack: "Next.js · Tailwind · API REST", url: "https://osa-website-alpha.vercel.app/", kind: "s" },
  { name: "Paroisse St Sauveur", image: "/assets/image/logo-paroise.png", purpose: "Back-office pour gérer les activités et les services d’une paroisse.", impact: "La gestion administrative est automatisée, ce qui allège le travail du personnel.", sector: "Back-office associatif", context: "Professionnel", stack: "Next.js · NestJS · PostgreSQL", url: "https://paroisse-st-sauveur-mis-ricordieux.vercel.app/", kind: "g" },
  { name: "Dri Valé — Gestion boutique", image: "/assets/image/drivale_logo.jpeg", purpose: "Caisse, stock, entrées et sorties, plus la vitrine en ligne d’une boutique de vêtements à Yopougon.", impact: "Le commerçant vend, suit son stock en temps réel et présente sa marque depuis une seule plateforme.", sector: "Commerce", context: "Freelance", stack: "NestJS · Prisma · CQRS", url: "https://dri-vale.online", kind: "g" },
  { name: "Stock-Pro", image: "/assets/image/stock.jpg", purpose: "Application de suivi des inventaires et des produits.", impact: "Elle aide à optimiser la gestion des stocks et à réduire les ruptures.", sector: "Gestion de stock", context: "Freelance", stack: "Next.js · React · Vercel", url: "https://stock-pro-six.vercel.app/stock", kind: "g" },
  { name: "Biblio UPB", image: "/assets/image/upb.jpg", purpose: "Plateforme de l’Université Polytechnique de Bingerville pour les administrateurs, les étudiants et les professeurs : documents, scolarité, notes et transport.", impact: "La vie universitaire est centralisée, la charge administrative baisse et les ressources pédagogiques sont plus accessibles.", sector: "Éducation", context: "Freelance", stack: "NestJS · Next.js · Prisma", url: "https://univeriste-polytechnique-de-bingerville.vercel.app/", kind: "g" },
  { name: "Application SOTRA", image: "/assets/image/Logo_sotra_2009.png", purpose: "Application de gestion interne conçue selon la méthode MERISE pour la Société de Transport Abidjanais, avec WinDev et SQL.", impact: "Les processus de gestion interne sont digitalisés et optimisés.", sector: "Transport", context: "Stage", stack: "WinDev · SQL · MERISE", url: "", kind: "g" },
  { name: "Projets MERN Stack", purpose: "Applications full-stack JavaScript réalisées pendant le bootcamp : APIs REST et interfaces dynamiques.", impact: "Elles montrent la maîtrise du développement JavaScript de bout en bout.", sector: "Formation", context: "Formation", stack: "MongoDB · Express · React · Node", url: "", kind: "s" },
  { name: "LUXTIME", purpose: "Application e-commerce avec catalogue, panier d’achat et paiement intégré.", impact: "Une interface d’achat moderne qui améliore l’expérience client en ligne.", sector: "E-commerce", context: "Professionnel", stack: "Next.js · Tailwind · API REST", url: "", kind: "s" },
  { name: "Maintenance Pro — SATE", image: "/assets/image/mainteance.png", purpose: "Gestion de la maintenance d’une flotte de véhicules : véhicules, techniciens, interventions et rapports, avec rôles administrateur et responsable de site.", impact: "Moins de pannes non traitées, des interventions entièrement tracées et des véhicules plus souvent disponibles.", sector: "Flotte de véhicules", context: "Professionnel", stack: "NestJS · Prisma · PostgreSQL", url: "https://maintenance-indol.vercel.app/", kind: "g" },
  { name: "Gestion Hôtel", image: "/assets/image/hotel.png", purpose: "Gestion d’un hôtel : chambres, réservations, clients et suivi financier.", impact: "Réservations, chambres et finances sont réunies dans une seule interface.", sector: "Hôtellerie", context: "Freelance", stack: "Next.js · Zustand · TanStack Query", url: "https://gestion-hotel-delta.vercel.app/dashboard", kind: "g" },
  { name: "Lunion Sécure Parcours", image: "/assets/image/logo_secure.png", purpose: "Gestion du personnel des entreprises de sécurité privée : back-office web, SaaS multi-clients et application desktop.", impact: "Présences, demandes et communication des agents sont suivies au même endroit.", sector: "Sécurité privée · SaaS", context: "Professionnel", stack: "Next.js · NestJS · Flutter", url: "", kind: "g" },
  { name: "Ephrata", image: "/assets/image/ephrata_logo.png", purpose: "Site vitrine d’un établissement scolaire : classes, galerie photo et palmarès des résultats.", impact: "Les parents et futurs élèves trouvent facilement l’information dont ils ont besoin.", sector: "Établissement scolaire", context: "Freelance", stack: "Next.js · GSAP · Framer Motion", url: "https://site-ephrata.vercel.app/", kind: "s" },
  { name: "Salam", purpose: "Site d’une mosquée : horaires de prière, calendrier islamique et vie communautaire.", impact: "Les fidèles accèdent aux horaires de prière facilement et la communauté reste connectée.", sector: "Lieu de culte", context: "Freelance", stack: "Next.js · API REST · Tailwind", url: "https://salam-taupe.vercel.app/", kind: "s" },
  { name: "Hôtel Poro — Korhogo", image: "/assets/image/hotel_korhogo.jpg", purpose: "Site vitrine et réservation en ligne pour l’Hôtel Poro à Korhogo, au cœur de la culture sénoufo.", impact: "Il valorise l’hôtel et la culture locale, et facilite la réservation par les clients.", sector: "Hôtellerie", context: "Freelance", stack: "Next.js · TanStack Query · Zod", url: "https://hotel-korhogo.vercel.app/", kind: "s" },
];
